apiwallet/src/lib.rs

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)   
--> apiwallet/src/lib.rs:37:9                                                                                          
|                                                                                                                     
36 | pub mod api;                                                                                                        
| ------------ not an extern crate passed with `--extern`                                                             
37 | pub use api::{APIForeign, APIOwner};                                                                                
|         ^^^ …
```

fix compile error

---

apiwallet/src/api.rs
libwallet/src/internal/restore.rs
libwallet/src/internal/updater.rs
libwallet/src/types.rs
refwallet/src/command.rs
refwallet/src/display.rs
refwallet/src/lmdb_wallet.rs
refwallet/tests/check.rs
refwallet/tests/transaction.rs
src/bin/cmd/wallet_args.rs
src/bin/cmd/wallet_tests.rs
src/bin/grin-wallet.yml

Changes to wallet info display and wallet check as described in https://github.com/mimblewimble/grin/issues/2520
* Unconfirmed non-coinbase outputs are added to an 'awaiting finalization' total in wallet info
* 'awaiting finalization' outputs don't appear in wallet total
* 'Unconfirmed' in the wallet info output are actually confirmed with < default number of confirmations
This only affects the output from the wallet info command and doesn't add any new internal states.
Also, wallet check no longer removes unconfirmed outputs and txs by default. A new flag 'delete_unconfirmed' is provided if the user wants to remove these.

'Awaiting finalization' status and changes to 'wallet check'

---

.hooks/pre-commit

`.hooks` folder is left behind when draw it from grin repo, which is needed for rustfmt hook.

add .hooks for rustfmt

---

api/src/foreign.rs
api/src/owner.rs
api/src/owner_rpc.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/types.rs
libwallet/tests/libwallet.rs
refwallet/src/command.rs
refwallet/src/controller.rs
refwallet/src/test_framework/mod.rs
refwallet/tests/accounts.rs
refwallet/tests/check.rs
refwallet/tests/file.rs
refwallet/tests/repost.rs
refwallet/tests/restore.rs
refwallet/tests/self_send.rs
refwallet/tests/transaction.rs

Previously, `initiate_tx` and `receive_tx` were returning callbacks that locked the wallet outputs. To support compatibility with json-rpc interface, changed this callback to be a regular function that gets info from the already stored context instead. 
Also added RPC wrappers for `initiate_tx` and `tx_lock_outputs`.

Remove callbacks from transaction API functions

---

.gitignore
controller/tests/transaction.rs
libwallet/src/internal/tx.rs

We currently default to generating `HeightLocked` transaction kernels (locked at current block height).
This PR changes this to default to generating `Plain` transaction kernels.
We are exploring making the lock_height optional on kernels (it is not included in the tx kernel hash for `Plain` kernels).
First step toward making them truly optional is to stop using them where we don't need to. 
Eventually we will be able to reduce storage and bandwidth costs (a little) by only including the `lock_height` on `HeightLocked` kernels.
This PR leverages the existing grin behavior - a `Plain` tx kernel default to a `lock_height` of 0 (as we need something to store in the u64 lock_height). This is excluded from the kernel hash for `Plain` kernels.
TODO -

default to using a Plain kernel with no lock_height

---

api/src/foreign_rpc.rs
api/src/lib.rs
api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/src/controller.rs
controller/tests/accounts.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/repost.rs
controller/tests/restore.rs
controller/tests/self_send.rs
controller/tests/transaction.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/owner.rs
libwallet/src/types.rs

Final round of changes and documentation for the V2 Owner API, most notably:
* move parameters for `initiate_tx` into a separate struct
* remove `estimate_initiate_tx` and roll functionality into the main `initiate_tx` function via a parameter
* add parameters to `initiate_tx` instructing API to exchange, finalize and post transactions in one go, to emulate the `send_tx` functionality in V1
* Clean up of documentation

Final Owner API Changes

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/lib.rs
api/src/owner.rs
api/src/owner_rpc.rs
controller/Cargo.toml
controller/src/command.rs
controller/src/controller.rs
controller/tests/accounts.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/repost.rs
controller/tests/restore.rs
controller/tests/self_send.rs
controller/tests/transaction.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/owner.rs
libwallet/src/types.rs

Enables the V2 json-rpc API, listening at
*`:3415/v2/foreign` 
and
*`:3420/v2/owner`
Full documentation contained in rustdoc

V2 API Enabling

---

controller/src/controller.rs
impls/src/adapters/http.rs
libwallet/src/slate.rs
src/bin/cmd/wallet_args.rs

Changes as a result of trying to send slates between different wallet versions. In the 1.1.0 code, all slates are serialized and sent as strings, to allow for differences between versions. Previously, they were serialized directly into a slate object, and the representation comes out differently after serde deser.
Bit of messiness has to go in to compensate for this for the time being (until 1.0.x series becomes completely obsolete), but for now the cases are handled and the following interactions should work:
* Sending a transaction from 1.1.0 to 1.1.0
* Sending a transaction from 1.0.x to 1.1.0 
* Sending a transaction from 1.1.0 to 1.0.x, provided the -v [target_slate_version] flag is specified in the send command (set this to 0 for compatibility with all older wallet clients)

Slate compatibility between versions

---

src/bin/cmd/wallet_args.rs

Fixes https://github.com/mimblewimble/grin-wallet/issues/40

Use correct wallet config in listen

---

README.md
api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/src/display.rs
controller/tests/transaction.rs
impls/src/backends/lmdb.rs
impls/src/lmdb_wallet.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/restore.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/internal/updater.rs
libwallet/src/types.rs
src/bin/cmd/wallet_args.rs
src/bin/cmd/wallet_tests.rs
src/bin/grin-wallet.yml

This reverts commit a63f2c7cea7392dfa91c8afdb0f912fd8c1b8aac, reversing
changes made to d774272fee41c6c1ab3ecefb86deacc109012471.

Revert "Merge branch 'master' into master"

---

api/src/foreign.rs
api/src/foreign_rpc.rs
api/src/owner.rs
api/src/owner_rpc.rs
api/tests/slate_versioning.rs
controller/src/command.rs
controller/src/controller.rs
controller/tests/accounts.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/invoice.rs
controller/tests/repost.rs
controller/tests/restore.rs
controller/tests/transaction.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/api_impl/types.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/lib.rs
libwallet/src/slate.rs

First attempt at supporting an invoiced transaction workflow, whereby the recipient generates a slate with an output for a certain amount, then sends the slate to a payer to fill in inputs and return. The aim of this PR is to add the API support (with some community feedback,) and implement the command line wallet functionality later. Much of the internal functionality to support this is already in place, so it's really just a case of getting the API structured correctly.
The way it's currently implemented here is:
* Add 2 functions to the owner api, `init_invoice_tx` and `receive_invoice_tx`. Receiving in the invoice case is being the person to add inputs to the slate, so it's an owner api function. It's assumed this will always be sent to the payer to view/verify before applying it to …

[WIP] Invoiced Transactions API Support

---

controller/src/command.rs
controller/tests/invoice.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v2.rs
src/bin/cmd/wallet_args.rs
src/bin/cmd/wallet_tests.rs
src/bin/grin-wallet.yml

Following from #90, the actual command line implementation exercising the invoice commands.
The code will mostly be a lot of boilerplate copying from the parsing and api execution system that's in place, but the particular file to watch for comments on the UI (if you can even call it that) is the command line arg yaml definition file:
`src/bin/grin-wallet.yml`

Command line implementation of invoice commands

---

Cargo.lock
controller/src/controller.rs
impls/src/adapters/file.rs
impls/src/adapters/http.rs
impls/src/adapters/keybase.rs
libwallet/src/error.rs
libwallet/src/slate.rs
libwallet/tests/slate_versioning.rs

- Previous deserialize method did multiple full deserializes. I added a `SlateVersionProbe` which only has to deserialize the relevant fields to figure out the version, after which full deserialization can be done.
- Implement `Serialize` on `Slate`, which serializes to the orig version. Use it in the adapters and the foreign API
- Simplify HTTP adapter, no longer require multiple serializes and deserializes
Still some testing to do, so marking as draft. Requesting review from @yeastplume

Simplify slate (de)serialization

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
impls/src/test_framework/testclient.rs
libwallet/Cargo.toml
util/Cargo.toml

* Update version to `1.1.0-beta.3`
* Build using grin tag `1.1.0-beta.2` as dependency instead of master
* Fix to call to grin Chain::init on latest Grin beta.2 tag,

Updates for 1.1.0-beta.3 release

---

impls/src/adapters/keybase.rs

Due to changes I made, slate responses were serialized twice by accident. This PR fixes that.

Fix keybase adapter

---

libwallet/src/api_impl/owner.rs

Invoice transaction payment error:
```
20190521 03:21:17.681 INFO grin_wallet_controller::command - Tx not created: Not enough funds. Required: 0.155000000, Available: 0.000000000
Wallet command failed: LibWallet Error: Not enough funds. Required: 0.155000000, Available: 0.000000000
```
but actually the current spendable balance is enough:
```
Currently Spendable              | 1.474000000 
```
The root cause is the slate `height`:
```
"amount": "150000000",
"fee": "0",
"height": "179846",
```
In case the payer has an output at height `179842` for example, and current chain height is `179942`, there will be a mistake judgement for `Spendable` with the origin slate height `179846`.
The fix solution is we always need update the slate height (to the latest height) on invoice pay function.

fix: invoice transaction pay need update the slate height

---

controller/src/controller.rs

I tested all permutations of sending/listening with v1.0.3 and v1.1.0 using HTTP and file. Turns out one of them wasn't working due to a double serialization, which is removed with this PR.
Fixes https://github.com/mimblewimble/grin-wallet/issues/108

Remove double json encoding on http response

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/src/controller.rs
controller/tests/accounts.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/invoice.rs
controller/tests/repost.rs
controller/tests/restore.rs
controller/tests/self_send.rs
controller/tests/transaction.rs
impls/src/backends/lmdb.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/types.rs
libwallet/tests/libwallet.rs

Mostly as a fix for self-sending invoices (but also for future needs where there are multiple parties in a transaction,) this adds a participant ID as a part of the key for stored private transaction context data. The slate id on its own isn't enough, as a party can act in multiple participant roles during a transaction.
Note there's currently an assumption throughout the code that participant 0 means 'party putting in funds' and 1 means 'party receiving funds'. This will need to be factored out in future and made more flexible.
Fixes https://github.com/mimblewimble/grin-wallet/issues/111

Add participant ID as part of key to stored private transaction context data

---

integration/Cargo.toml

For some reason using grin-wallet as a dependency scans the `integration/Cargo.toml` as well, even though it is excluded in the main Cargo file...

Disable old dependencies in integration crate

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
libwallet/Cargo.toml
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/types.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v2.rs

1) This removes `default_slate_version` from the structure returned from the foreign api's `check_version`, and instead returns an enumeration of slate versions supported. This is implemented in such a way as to ensure it can't be forgotten about, i.e. it will return the list directly from the variants in the internal SlateVersions enum.
In thinking about slate versioning a bit more, this approach to how the `check_version` function should behave seems more natural to me. A caller can query which versions are supported and report the exact issue if it can't negotiate a match.
2) Also removes the `min_compat_version` from the slate, as on further thinking I'm not sure how it would be needed or why it would be used.

Version Info API Function tweak, remove 'min_compat_version' from slate

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
controller/src/command.rs
impls/src/node_clients/http.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v2.rs
libwallet/tests/slates/v2.slate
src/bin/cmd/wallet.rs
src/bin/cmd/wallet_args.rs
util/Cargo.toml

1.1.0 Changes resulting from dev meetings over the past couple of days. All points are outlined below, but checklist for this PR only applies to 1.1.0.
Also, in addition to checklist below:
* Clean some compiler warnings during test
* Change misleading output saying that slate was sent when it was actually just being output to file
* Update API doctests to reflect signature format change and output features change grin-side
Grin-wallet 2.0.0 will fill the `block_header_version` field of the slate as 2
Grin-wallet 2.0.0 will refuse to process slates with a `block_header_version` of 1.0
Grin-wallet 2.0.0 will not post transactions to a grin node reporting a current block height < HF height
Grin-wallet/Grin node v2.0.0 will have a node API tweak to ensure grin-wallet 1.1.0 cannot communicate …

Changes for 1.1.0 -> 2.0.0 Deployment strategy decisions

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
libwallet/src/internal/tx.rs

- Cargo.lock is left behind
- 1.35.0 build warnings

cargo.lock update, and remove 3 build warning from cargo 1.35.0

---

impls/src/adapters/http.rs

Implements a call to the v2 api's `check_version` function before attempting an HTTP send, and reports a useful error if the API doesn't exist or reports an unsupported slate version.

V2 API conversion Pt2 - Check version

---

Cargo.lock
Cargo.toml
api/src/foreign.rs
api/src/foreign_rpc.rs
api/src/lib.rs
api/src/owner_rpc.rs
controller/src/controller.rs
impls/src/node_clients/http.rs
impls/src/test_framework/testclient.rs
libwallet/src/error.rs
libwallet/src/internal/tx.rs
libwallet/src/lib.rs
libwallet/src/types.rs
src/bin/cmd/wallet.rs

Follow up from https://github.com/mimblewimble/grin/pull/2897 on the wallet side
* Change `v1/pool/push` endpoint call to `v1/pool/push_tx`
* Add function to read version info from node to NodeClient trait, add implementation to HttpNodeClient
* On startup, attempt to read version info from node and:
* If can't communicate with node, continue read only
* If node reports 404 for `v1/version` endpoint, assume node is < 2.0.0 and exit
* If node reports version < what wallet is looking for as a minimum (currently 2.0.0-beta.1), exit with message to upgrade
* ~~If node reports blockheader version < what wallet is looking for (currently set to 1 for testing, but should be bumped to 2 before releasing), exit with prompt to upgrade~~

Read version info from server, react accordingly

---

impls/src/adapters/http.rs

If older wallet is 1.0.x series (i.e. doesn't have the v2 API version function in place,) provide a more specific message.

Provide more specific error when other wallet is outdated

---

src/bin/grin-wallet.rs
src/bin/grin-wallet.yml

The version reported by `grin-wallet --version` is currently set manually in `grin-wallet.yml`, which means it can easily be missed on release. Small fix to ensure this output comes from the cargo package version instead.

Derive --version output dynamically from cargo package version

---

controller/src/command.rs
src/bin/cmd/wallet_args.rs
src/bin/cmd/wallet_tests.rs
src/bin/grin-wallet.yml

add --txid to the `wallet txs` command

---

api/src/owner_rpc.rs

Resolves #201 
Takes the same approach as the foreign_rpc api where we use `VersionedSlate` on the rpc side of things, converting to `Slate` internally.
These both serialize/deserialize in an identical fashion currently so this does not affect anything.
But once we start modifying `Slate` itself (via the contained `Transaction`) we should be decoupled from these changes.

use VersionedSlate for the owner_rpc api

---

api/src/foreign_rpc.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/types.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v2.rs
libwallet/src/types.rs

This PR introduces a `VersionedCoinbase`, following the same approach as the existing `VersionedSlate`.
We have a `build_coinbase` api call on the foreign api that is used by a mining node to generate a new coinbase reward (output + kernel) when building a candidate block for mining.
It is important this api continues to work even if we make internal changes to the core output and kernel impls.
The `build_coinbase` api endpoint now returns a `VersionedCoinbase` (currently uses `V2`) and this maintains full backward compatibility with the existing node and wallet.
This api endpoint is a little tricky and easy to miss because it works in the opposite direction to everything else. This is accessed `node->wallet` when generating candidate blocks for mining.
This PR should add some additional …

Introduce VersionedCoinbase to add api stability around build_coinbase

---

api/src/owner.rs
api/src/owner_rpc_s.rs
impls/src/lifecycle/default.rs
impls/src/lifecycle/seed.rs
libwallet/src/types.rs
tests/common/mod.rs
tests/data/v3_reqs/change_password.req.json
tests/data/v3_reqs/create_wallet.req.json
tests/data/v3_reqs/delete_wallet.req.json
tests/owner_v3_lifecycle.rs

Implementations of final lifecycle API functions as defined in https://github.com/mimblewimble/grin-rfcs/blob/master/text/0004-full-wallet-lifecycle.md
* `get_nmemonic` returns the mnemonic for a given wallet and provided password
* `change_password` re-generates a wallet's `wallet.seed` file, and encrypts it with a new password. It temporarily backs up the old `wallet.seed` file and performs an extra verification step ensuring the seeds are equal before deleting the old file.
* ` delete_wallet` removes an entire wallet directory. Users and developers should be extra careful when using this one, obviously.
Reference #212

API Lifecycle Implementation, Part 2

---

impls/src/backends/lmdb.rs
impls/src/test_framework/testclient.rs
libwallet/src/api_impl/owner.rs

This is a bit tricky.
A 2.1.0 node uses protocol version 2 internally via `ProtocolVersion::local()`.
But for backward compatibility expects txs via the push api (from the wallet) in proto version 1.
Building grin-wallet pulls in `ser` from node repo.
So we cannot use `ProtocolVersion::local()` in the wallet repo.
This only surfaced as an issue once we tagged node and wallet repos and started building against these.

use explicit protocol version (local is not safe)

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

For continuing development, `current/2.1.x` has been created for 2.1.0 release/maintenance

Update version to 3.0.0-alpha.1

---

Cargo.lock
impls/Cargo.toml
impls/src/adapters/http.rs
impls/src/adapters/mod.rs

Unintended consequence of earlier changes to how urls are handled meant that everything but the base URL was being stripped when sending to another wallet. This fix reverts to earlier behaviour, keeping the entire URL+Path intact.
Going to merge into master first, then cherry-pick into the `current/2.1.x` branch

Fix URL Compatibility with 2.0.0

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
libwallet/src/types.rs
util/Cargo.toml

Fixes backwards compatibility issue discovered when sending to Poloniex with a 2.1.0 wallet. New fields being read from the DB didn't have a Serde default and were silently returning no transaction data when querying transactions created in  < 2.1.0

2.1.0 TX log entries backwards compatibility fix

---

Cargo.lock
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs

Resolves #248 
Related https://github.com/mimblewimble/grin/pull/3057 (must be merged before this PR)
We no longer use tx building combinators for fee and lock_height.
We now pass an existing tx into `build::partial_transaction`.
We are also responsible for updating the tx kernel to reflect the features based on the current slate (fee changes based on the tx being built).
The motivation for these changes is to increase the flexibility to support future kernel feature variants, specifically "relative height locked" kernels.
The tx building combinators `with_fee` and `with_lock_height` did not fit cleanly with adding new feature variants as the different combinations of optional fields (fee, lock_height etc.) produce different kernel features.

Tx combinator refactor

---

controller/src/command.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

This PR adds the ability to finalize a transaction without posting the transaction to the chain, and separately post a finalized slate to the chain.
1) **For air-gapped wallets**: Currently there is no easy way to send transactions from an offline/air-gapped wallet. To finalize a transaction, the wallet requires a connection to a running node. With this feature, it is now possible to generate a finalized slate on an offline machine (without posting to chain), copy that slate file to another machine (with a connected Grin node), and post the transaction on that machine.
2) **For sender privacy**: Currently, the sender must reveal his IP to the network (or at least to one connected node) during transaction finalization. With this feature, a transaction sender no longer needs to reveal …

Add option to finalize and post transactions separately (for air-gap wallets)

---

api/src/foreign_rpc.rs
api/src/owner.rs
api/src/owner_rpc.rs
api/src/owner_rpc_s.rs
controller/src/command.rs
controller/src/controller.rs
controller/tests/updater_thread.rs
impls/src/backends/lmdb.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl.rs
libwallet/src/api_impl/owner.rs
libwallet/src/api_impl/owner_updater.rs
libwallet/src/internal/scan.rs
libwallet/src/lib.rs
src/bin/grin-wallet.yml
tests/common/mod.rs
tests/owner_v3_lifecycle.rs

Continuing work as per RFC at https://github.com/mimblewimble/grin-rfcs/pull/30. This PR:
* Adds functions to the owner API to stop and start the updater thread
* Modifies other functions that might update the wallet to not attempt update if the updater thread is running
* Modifies utxo scanning to send status update messages to an mpsc sender instead of logging
* Provide functions to return status update messages
* changes default selection strategy to 'smallest'
* Test additions and updates

Add updater thread + Updater related functions

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
api/src/owner_rpc_s.rs
controller/src/command.rs
impls/src/adapters/http.rs
impls/src/test_framework/testclient.rs
libwallet/Cargo.toml
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v3.rs
tests/owner_v3_lifecycle.rs

This PR aims to include all slate changes for HF2 in a single place. These changes are:
* Addition of the `payment_proof` struct as outlined in https://github.com/mimblewimble/grin-rfcs/pull/31 - This is an option field and contains
* `sender_address` - an ed25519 Public key
* `receiver_address` - an ed25519 Public key, optional as it will be filled at some stage in the exchange process, not necessarily up front
* `receiver_signature` - secp256k1 Schnorr signature, optional for the same reason
* `message` as outlined in the RFC not included, pending (or rather not) based on discussion of the significant drawbacks to including it.
* Addition of `ttl_cutoff_height` as described in https://github.com/mimblewimble/grin-rfcs/pull/30
Note while it's perfectly possible now to detect and convert …

HF2 Slate Changes

---

README.md

Looks like this:
[![](https://img.shields.io/badge/dynamic/json.svg?label=docs&uri=https%3A%2F%2Fcrates.io%2Fapi%2Fv1%2Fcrates%2Fgrin-wallet%2Fversions&query=%24.versions%5B0%5D.num&colorB=4F74A6)](https://docs.rs/releases/search?query=grin+wallet)
Pointing to the search result on rust doc.

Add link to rustdoc instead of wiki

---

README.md
libwallet/src/internal/tx.rs
tests/cmd_line_basic.rs

As pointed out by @DavidBurkett, the stored proof needs to be checked if the proof in the slate is None, otherwise the recipient could just remove the proof.

Check stored transaction for payment proof when checking proof

---

src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

As explained in https://github.com/mimblewimble/grin-wallet/issues/251, this is renamed to alleviate confusion.

Rename `data_dir` command line switch to `top_level_dir`

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/tests/updater_thread.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/scan.rs

A few smaller items in one go rather than creating several micro PRs. Will keep this updated as I go
* Add a deprecation warning for the V2 Owner API.
* Fix scan output not appearing when running `grin-wallet scan`
* Fix scan percentage complete calculation in reported messages, fix message being sent twice per iteration

Bits and Pieces for 3.0.0 beta

---

api/src/foreign_rpc.rs
controller/src/command.rs
controller/src/controller.rs
impls/src/adapters/file.rs
impls/src/adapters/http.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v2.rs
libwallet/src/slate_versions/v3.rs
src/bin/grin-wallet.yml

This restores wallet-to-wallet compatibility between V3.0.0 and V2.0.0 by re-introducing the V2 slate. The rules for conversion are:
When sending via HTTP (including TOR), the slate version on the remote side is checked and:
* If V3 support is reported back, send slate as a V3 slate
* If V2 only is reported back:
* Downgrade slate to V2 before sending if `payment_proof` is None
* If `payment_proof` is Some then stop the transaction with an error saying proofs aren't supported by the other side
* If `ttl_cutoff_height` is some, warn the user that it will be ignored by the other side and dropped by them in the slate, but continue to downgrade to V2
When outputting a file (either via send or invoice):
* If both `payment_proof` and `ttl_cutoff_height` are None, downgrade slate to V2 before …

V2 Slate Compatibility

---

Cargo.lock
Cargo.toml
api/Cargo.toml
api/src/owner_rpc.rs
api/src/owner_rpc_s.rs
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Versioning + Cargo.lock changes for 3.0.0. Will update with tag of Grin 3.0.0-beta.1 when it's tagged

3.0.0-beta.1 Versioning

---

impls/src/node_clients/http.rs

As reported here https://www.grin-forum.org/t/wallet-error-when-checking-balance/6840/2 and on keybase, older chain data appears to be pulling outputs directly from the utxo set but returning them as spent. Not attempting any logic changes this close to release, but this removes the unwraps mentioned in the trace below and should log full information about the error when it occurs. Conversation below for reference.
```
There seems to be something odd going on in older node data... the stacktrace reported in the ecosystem channel is as follows: 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/libcore/option.rs:378stack backtrace:
0: backtrace::backtrace::trace
1: backtrace::capture::Backtrace::new
2: grin_util::logger::send_panic_to_log::{{closure}}
3: …
```

Better error handling during UTXO Scan

---

.hooks/pre-commit
src/cmd/wallet.rs

Fixes node version check on startup to correctly look for a 3.0.0, which was overlooked prior to 3.0.0 release. Shouldn't be a huge problem in practice since everyone needs to update to 3.0.0 anyhow, but included for correctness.
Also updates the pre-commit hook to the version in grin, which rustfmts on commit instead of needed to perform a separate commit.
To be cherrypicked to master

Version check fix + Rustfmt

---

libwallet/src/api_impl/owner_updater.rs

Log update thread do not exit after call ownerAPI.

Fix: Log update thread do not exit after call ownerAPI.

---

libwallet/src/api_impl/owner_updater.rs

Fix: Log update thread do not exit after call ownerAPI. (#284)

---

impls/src/node_clients/http.rs

Changes the hardcoded 200 in the default node client's `get_outputs` query to optionally use an environment variable, so users have a lever with which to try to address URI length restrictions in their environments.
Note this is done as an environment variable as opposed to a configuration setting, as this is only intended to be a temporary workaround. The move to using the node's JSON-RPC API will happen on or before 4.0.0 and should address the root of this issue properly (by including the list of outputs to fetch in the body instead of as a query string).

Add output query chunk size as temporary env variable

---

impls/src/node_clients/http.rs

Add output query chunk size as temporary env variable (#298)

---

Cargo.lock
doc/design/design.md
impls/src/lifecycle/seed.rs
impls/src/node_clients/http.rs

**Background**
I believe that at some point people separated Grin Wallet from Grin and moved it into its own grin-wallet repository; however, some user-facing references to "grin wallet" remain.
**Changes**
I changed some user-facing instances of "grin wallet" to "grin-wallet"
**Rationale and scope**
I only changed instances of "grin wallet" where the user gets a direct instruction from grin-wallet. I focused on only those instances because the user should get correct and unambiguous instructions from grin-wallet. I left unchanged any "grin wallet" instances that would fall only under the purview of brand such as whether to use the words "Grin wallet", "Grin Wallet", "grin wallet", "the grin wallet", etc.

Grin hypen wallet

---

api/src/owner.rs
api/src/owner_rpc.rs
api/src/owner_rpc_s.rs
controller/src/command.rs
controller/tests/payment_proofs.rs
impls/src/test_framework/testclient.rs
libwallet/src/api_impl/owner.rs
libwallet/src/api_impl/types.rs
libwallet/src/error.rs
libwallet/src/internal/tx.rs
libwallet/src/lib.rs
libwallet/src/slate_versions/ser.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Aims to add functionality to the API to export payment proofs as JSON and validate an exported payment proof, as well as command-line options calling both.
Update on completion:
* Adds a `PaymentProof` struct intended for serialization into JSON for export to file or use via the API
* Adds needed serializer for payment proof struct
* Adds new API functions `retrieve_payment_proof` and `verify_payment_proof` (details in rustdoc documentation, as well as supporting internal implementations
* Adds `export_proof` and `verify_proof` command line options
* Documentation + doctests for all of the above

Payment Proof export + validation

---

api/src/types.rs
controller/src/controller.rs
tests/common/mod.rs

Fixes #312 and #313.
uint64 are now serialized as string and can be deserialized either from integer or string.

Secure API JSON RPC ID can be integer or string

---

libwallet/src/api_impl/types.rs

Fixes https://github.com/mimblewimble/grin-wallet/issues/310, turns out the custom specifiers were stripping the fields of all the serde-derived behaviour, so a the default specifier needs to be specifically included.

Add `serde(default)` specifier to fields to send tx args

---

config/src/config.rs
config/src/lib.rs
config/src/types.rs
src/bin/grin-wallet.rs
src/cmd/wallet_args.rs
tests/common/mod.rs

Reworks initial directory setup logic and the flow of the `init` command to:
* That the `--top-level-dir` switch is respected appropriately
* That the api secret files aren't written to default locations when using the `--top-level-dir` switch or initting a wallet in the current directory (these were erroneously being created in the `~./grin/main` dirs)
* Check for the presence of an existing configuration file *before* asking user for a password/recovery phrase, and exit if so.
Fixes #308 and #279

Rework directory checks/setups at launch

---

api/src/owner_rpc_s.rs
impls/src/lifecycle/default.rs
impls/src/lifecycle/seed.rs
tests/data/v3_reqs/create_wallet_invalid_mn.req.json
tests/data/v3_reqs/create_wallet_valid_mn.req.json
tests/owner_v3_lifecycle.rs

Fixes #292, call to `WalletSeed::init_file` was swallowing its error and continuing.
Adds explicit tests to exercise `create_wallet` with both valid and invalid seeds.

Ensure API `create_wallet` returns failure when provided with invalid mnemonic seeds

---

Cargo.lock
Cargo.toml
api/src/foreign.rs
api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/src/controller.rs
controller/src/error.rs
controller/tests/accounts.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/invoice.rs
controller/tests/no_change.rs
controller/tests/payment_proofs.rs
controller/tests/repost.rs
controller/tests/self_send.rs
controller/tests/transaction.rs
controller/tests/ttl_cutoff.rs
controller/tests/updater_thread.rs
libwallet/src/api_impl/owner_updater.rs
src/bin/grin-wallet.rs
src/bin/grin-wallet.yml
src/cli/cli.rs
src/cli/mod.rs
src/cmd/wallet_args.rs
src/lib.rs
tests/cmd_line_basic.rs
tests/owner_v3_lifecycle.rs

The goal of the PR will be to have all of the command line options working in CLI mode at a basic level, perhaps not all polished or perfect with respect to their functionality. 
It's important to note that this adds command line functionality while leaving the existing single-invocation mode functionality intact. The CLI functionality can be introduced, then refined and tweaked over time without any impact on existing functionality.
The focuses of this PR are:
* Provide a basic command-prompt mode for all existing wallet actions without duplicating code or functionality.
* Ensure the commands and switches are consistent between the CLI and single-invocation mode (except for commands that only make sense in one or the other)
* Ensure the CLI mode is backed by a single static instance of …

Wallet Interactive-mode, Part 1

---

Cargo.lock
controller/src/command.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Adds the `--backwards_from_tip` switch to the scan command, to allow users to specify the beginning scan height relative to the current tip.
Addresses #320

Add ability to specify scan height backwards from tip

---

Cargo.lock
impls/Cargo.toml
impls/src/adapters/http.rs
impls/src/client_utils/client.rs
impls/src/client_utils/json_rpc.rs
impls/src/client_utils/mod.rs
impls/src/lib.rs
impls/src/node_clients/http.rs
impls/src/node_clients/resp_types.rs
impls/src/test_framework/testclient.rs
libwallet/src/api_impl/owner.rs
libwallet/src/types.rs

Work in progress, includes new JSON-RPC client library code.
Will address #305

Convert node client to use V2 Node API

---

impls/src/client_utils/client.rs
impls/src/node_clients/http.rs

Each request was spawning its own multithreaded runtime that kept running even after the request was done, taking up resources unnecessarily. This PR addresses that, by using a runtime that runs in the current thread.
Ideally we would have a single multithreaded runtime to spawn all requests on, but that is a larger refactor that I'm planning on doing later on.
Small side note is that the current-thread runtime is only active until the future completes and any unfinished tasks that were spawned by this future aren't polled anymore. Since we are not spawning any tasks that outlive our future this shouldn't have any effect but it is something to keep in the back of our minds.
Fixes https://github.com/mimblewimble/grin-wallet/issues/330

Shutdown runtime after task is completed

---

Cargo.lock
impls/src/backends/lmdb.rs
impls/src/client_utils/client.rs
libwallet/src/address.rs
libwallet/src/internal/tx.rs
libwallet/src/internal/updater.rs
libwallet/tests/libwallet.rs

* Update with latest upstream Grin dependencies in Cargo.lock
* libtx functions now require a SwitchCommitment as opposed to a reference.

Cargo update

---

api/src/lib.rs
api/src/types.rs
controller/src/controller.rs
libwallet/src/slate_versions/ser.rs
tests/common/mod.rs
tests/owner_v3_init_secure.rs
tests/owner_v3_lifecycle.rs

(Replaces #334, with a saner commit history)
In doing some sample code for the V3 API, it became evident that the ID field in encrypted requests shouldn't be restricted to being a u64, or a string representation of a u64. It should allow all types of IDs in so long as they're strings, including UUIDs.
This changes the EncryptedRequest/Response fields to type String, and provides a custom legacy serializer to ensure anyone currently sending ids as ints won't be affected by the change.

Change EncryptedRequest 'id' field to String

---

doc/samples/v3_api_node/package-lock.json
doc/samples/v3_api_node/package.json
doc/samples/v3_api_node/readme.md
doc/samples/v3_api_node/src/index.js

Adds a small sample project to the `docs` directory with sample code to initialize the secure V3 owner API and call its functions.
Should be useful for reference or adaptable into a small test-harness if required.

Add sample script to init and call the secure owner API from node.js

---

Cargo.lock
api/src/types.rs
controller/src/controller.rs
impls/Cargo.toml
impls/src/client_utils/client.rs
impls/src/node_clients/http.rs

- Move controller over to futures0.3 using async/.await
- Add size check in secure owner api nonce
- Due to mixed blocking and async usage within the wallet, we have to use scoped threads to create a new runtime for node api calls. This is kind of an unfortunate situation, but preventing it would require a larger refactor on the wallet, so we're leaving it for a future PR

Fix controller, node api calls

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
controller/tests/file.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4.rs

* Removes unnecessary de/ser directives from internal Slate object
* Serializes `version_info` field as `ver` in "[version].[block_header_version]" format
* Removes SlateVersionProbe (slate can be upgraded to latest by deserializing an enum
* Update doctests

Compact Version Field + Remove unnecessary Slate deser directives

---

Cargo.lock
api/src/foreign_rpc.rs
controller/tests/file.rs
libwallet/Cargo.toml
libwallet/src/slate.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4.rs

* Serializes all binary fields in SlateV4 and TransactionV4 as base64 instead of hex encoding
* Rename `amount` -> `amt`
* Rename `participant_data` -> `sigs`
* Rename `sigs` fields ->
* `public_blind_excess` -> `xs`
* `public_blind_nonce` -> `nonce`
* `part_sig` -> `part`
* Compacts the TransactionV4 struct within the slate:
* skip serializing `offset` if blank
* skip serializing `body.inputs` if empty
* rename `body.inputs` to `body.ins`
* skip serializing `body.outputs` if empty
* rename `body.outputs` to `body.outs`jjkk
* skip serializing Inputs and Outputs 'features` if the types is `OutputFeatures.Plain`
* skip serializing kernel features if the type is `CompatKernelFeatures.Plain`
* skip serializing kernel `fee` if 0
* skip serializing kernel `lock_height` if 0
* skip serializing …

Compact transaction object and Base64 binary fields

---

impls/src/adapters/file.rs
impls/src/adapters/http.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4.rs

* Remove height field from Slate and Slate V4
* Retrieve height from tip where required for coin selection
* Remove all direct ser/deser derivations from Slate

Remove height field from Slate and SlateV4

---

libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4.rs

As titled, shaving the ID to 24 bytes

Serialize V4 ID field in Slate as Base64

---

controller/tests/invoice.rs
controller/tests/payment_proofs.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/slate_versions/v4.rs
libwallet/src/types.rs

Sets amount and fee on the slate to 0 where not needed, with each participant keeping the info in their transaction context instead. 
S1 -> amount and fee specified
S2 -> amount and fee removed
S3 -> amount and fee removed
I1 -> amount specified
I2 -> amount removed, fee specified
I3 -> amount and fee removed

Remove amount and fee from Slate where not needed

---

controller/src/command.rs
controller/tests/file.rs
libwallet/src/api_impl/types.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4.rs
src/cmd/wallet_args.rs

Final (for now) changes for compact V4 Slate: 
* Add tests that output all types of slate as files
* Ensure `None` rangeproofs` aren't serialized for inputs
* Shorten OutputFeatures serialization (1 for CoinBase, 0 otherwise)
* Rename payment proof fields as per RFC
* Base 64 encoding of payment proof elements

Final Changes for compact Slate

---

Cargo.lock
controller/src/command.rs
controller/tests/check.rs
controller/tests/file.rs
controller/tests/repost.rs
controller/tests/revert.rs
impls/src/adapters/file.rs
impls/src/adapters/mod.rs
impls/src/client_utils/byte_ser.rs
impls/src/client_utils/mod.rs
libwallet/src/api_impl/types.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v4.rs
libwallet/src/slate_versions/v4_bin.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs
tests/cmd_line_basic.rs

WIP Serialization code to test the feasibility of serializing slates to binary format. It should be possible given the following rules. (Whether we want to allow it is another discussion)
* The internal slate object remains unserializable.
* The first-order slate object is still the JSON form. Upgrading and downgrading slates between versions still happens between VersionedSlate structs.
* Each VersionedSlate version can additionally output itself in binary form, converting between binary and its Versioned self, so SlateV4Bin <--> SlateV4 is possible. (But since the VersionedSlates are handling all upgrade conversions, there is no need to provide conversion functions between binary slate versions)
When outputting a Slate to a file, it should be possible to specify a `.bin` flag to spit it …

Binary Slates

---

controller/tests/file.rs
controller/tests/no_change.rs
impls/src/client_utils/json_rpc.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/slate.rs
libwallet/src/types.rs

When sending back the S2 or I2 invoice in the exchange, it's not necessary to re-include the initiators public excess and nonce values. This removes these values from the slate during the I2 and S2 phases, relying on each party to restore them when needed.

Remove unneeded signature data during S2 and I2 stages

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/repost.rs
controller/tests/transaction.rs
impls/src/backends/lmdb.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/tx.rs
libwallet/src/types.rs

* Modifies `get_stored_tx` to accept a UUID instead of a `TxLogEntry`
* Ensures the result is a core `Transaction` object instead of a TransactionV4

Update get_stored_tx to accept UUID instead of full transaction log entry

---

api/src/foreign_rpc.rs
api/src/owner_rpc.rs
libwallet/src/slate_versions/v4.rs

After some testing and thought, it's more desirable to leave the slate's Uuid in its standard form to make it easier to match it up with entries in the transaction log. The alternative is to change the output of the ID everywhere to the base64 representation, but this would be very non-standard for presenting a uuid.
Further, since we now have binary serialization which simply outputs the uuid bytes for applications where a minimal slate size is desirable, the bytes saved don't achieve any particular result.

Revert slate id serialization to hex-string uuid

---

api/src/foreign_rpc.rs
controller/src/command.rs
impls/src/adapters/file.rs
impls/src/adapters/http.rs
impls/src/adapters/mod.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v3.rs
libwallet/src/slate_versions/v4.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

This PR should cover whatever changes are necessary to ensure communication with V3 wallets continues to work for the period between the release of v4.0.0 and the date of HF3. Note that quite a bit of this will be temporary code, to be removed shortly after HF3.

v3.x.x - v4.0.0 wallet compatibility fixes

---

controller/tests/payment_proofs.rs
controller/tests/transaction.rs
libwallet/src/error.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4.rs
libwallet/src/slate_versions/v4_bin.rs

This removes `lock_height` and adds a kernel features flag + kernel arguments struct. See the Compact slates RFC for details.

Remove lock_height, add kernel_features + arguments

---

Cargo.lock
api/src/foreign.rs
api/src/foreign_rpc.rs
api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/common/mod.rs
controller/tests/updater_thread.rs
impls/src/lifecycle/default.rs
impls/src/test_framework/testclient.rs
integration/tests/api.rs
integration/tests/dandelion.rs
integration/tests/simulnet.rs
integration/tests/stratum.rs
src/bin/grin-wallet.rs
src/cmd/wallet_args.rs
tests/common/mod.rs
tests/owner_v3_init_secure.rs
tests/owner_v3_lifecycle.rs
tests/tor_dev_helper.rs

Replaces #409 (closed due to merge/rebase problems).
Related https://github.com/mimblewimble/grin/pull/3327
Grin PR https://github.com/mimblewimble/grin/pull/3327 introduces (thread) local and global configuration of `chain_type`.
This PR makes the necessary changes in grin-wallet for compatibility.
----
Updated grin deps for latest master -
```
cargo update -p grin_core
Updating git repository `https://github.com/mimblewimble/grin`
Updating crates.io index
Updating grin_api v4.0.0-alpha.1 (https://github.com/mimblewimble/grin#93f5de3d) -> #6faa0e8d
Updating grin_chain v4.0.0-alpha.1 (https://github.com/mimblewimble/grin#93f5de3d) -> #6faa0e8d
Updating grin_core v4.0.0-alpha.1 (https://github.com/mimblewimble/grin#93f5de3d) -> #6faa0e8d
Updating grin_keychain v4.0.0-alpha.1 …
```

local vs global chain_type (for better test isolation)

---

Cargo.lock
controller/Cargo.toml
controller/tests/slatepack.rs
impls/src/adapters/mod.rs
impls/src/adapters/slatepack.rs
impls/src/lib.rs
libwallet/Cargo.toml
libwallet/src/error.rs
libwallet/src/lib.rs
libwallet/src/slatepack/address.rs
libwallet/src/slatepack/armor.rs
libwallet/src/slatepack/mod.rs
libwallet/src/slatepack/packer.rs
libwallet/src/slatepack/types.rs

* Adds the `SlatepackAddress` struct as specified in the slatepack RFC with all required conversion and serialization functions.
* Replaces x25519 keys in the slatepack struct with `SlatepackAddress`
* Refactors Slatepack functions into libwallet in anticipation of adding slatepack functions to the API.

Slatepack Pt. 3 - The Packening (SlatepackAddress implementation)

---

libwallet/src/slatepack/armor.rs
libwallet/src/slatepack/packer.rs

This PR improves support for line formatting for an armored `SlatepackMessage` as specified in the [RFC](https://github.com/mimblewimble/grin-rfcs/pull/55). 
Note that the `HEADER` is a 'word' for the purposes of formatting (and was specifically chosen to be the same length as the default `WORD_LENGTH`). Otherwise the first line in the output is off by one word and doesn't look nice (this could be approached by making `format_slatepack()` smarter instead but this seemed easier given our existing choices and needs).
After thinking through 'multipart' messages more I'd like to propose some armor changes for handling edge cases of large txs (which shouldn't require changes to existing slatepack impl work beyond this PR):
- Remove support for 'multipart' `SlatepackMessage`
- Add default 1MB …

Slatepack armor formatting

---

api/src/lib.rs
api/src/owner.rs
api/src/owner_rpc.rs
api/src/types.rs
controller/src/command.rs
controller/tests/file.rs
controller/tests/payment_proofs.rs
controller/tests/slatepack.rs
impls/src/adapters/slatepack.rs
libwallet/src/api_impl/owner.rs
libwallet/src/api_impl/types.rs
libwallet/src/error.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slatepack/address.rs
libwallet/src/slatepack/packer.rs
libwallet/src/slatepack/types.rs
src/cmd/wallet_args.rs

This PR aims to:
* Expose Slatepack changes via the OwnerAPI
* Ensure all user-facing instance of addresses in the API use a SlatepackAddress. This means that what was previously either being input/output by the user as a payment proof address or TOR address will now be a Slatepack address.
In detail:
New API functions are:
* `create_slatepack_message` - returns an (optionally encrypted) armored slatepack string from a slate 
* `slate_from_slatepack_message` - extracts the slate from the given slatepack string, attempting to decrypt from a range of deriviation indices if necessary (takes a vec instead of a single value for future multiple-address use)
* `decode_slatepack_message` - convenience function that returns the Slatepack struct itself, which can be viewed as json.
Notes: 
* The …

Slatepack OwnerAPI Changes

---

Cargo.lock
libwallet/src/error.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4.rs
util/Cargo.toml

* add mapping for new NRD kernel feature variant
* build against master branch of grin
Related issue: #393

NRD kernel variant (compile against grin master)

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Equivalent of #422 for current/v3.1.x + version bump to 3.1.2.
Do Not Merge because it would be much better to release grin-wallet v3.1.2 with grin v3.1.1 which is still no published on crates.io.

[3.1.x] Fix Tor send

---

Cargo.lock
impls/Cargo.toml
impls/src/client_utils/client.rs

Update to use new MW fork of hyper-socks2 crate

Update hyper-socks2 to versioned crate

---

controller/tests/slatepack.rs
libwallet/Cargo.toml
libwallet/src/slatepack/address.rs
libwallet/src/slatepack/types.rs

Adds encrypted metadata to the slatepack definition, which works as follows:
* Encrypted metadata isn't serialized separately, it's rather prefixed to the slate payload on encrypt, and split off on decrypt.
* On encryption, the sender field is moved from the unencrypted header into the encrypted metadata field, and is moved back on decryption. This means that anyone using the struct only needs to worry about setting the sender field in one place.
* Recipients can be added to the Slatepack, but if the payload is not encrypted they won't be included in serialization (as they can only exist in the payload of an encrypted slate)
Also includes
* Slatepack function to add recipients
* Tests ensuring that `SlatepackEncMetadata` struct will continue to parse correctly when additional fields are …

Encrypted Slatepack Metadata

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/slatepack.rs
impls/src/adapters/slatepack.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slatepack/packer.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

* Adds a `grin-wallet unpack` command, which unpacks a slatepack message, decrypts (if it's intended for this wallet), and displays the slate in JSON (if possible)
* Cleans up some of the command-line help text to reflect Slatepack changes

Add unpack command

---

libwallet/src/slate_versions/v4.rs
libwallet/src/slate_versions/v4_bin.rs

// Match on kernel feature variant:
// 0: plain
// 1: coinbase (invalid)
// 2: height locked (with associated lock_height)
// 3: NRD (with associated relative_height)
// Anything else is unknown.

Fix: height locked feature value should be 2.

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/slatepack.rs
libwallet/src/api_impl/owner.rs

Fixes #442 by reworking the `decode_slatepack` API function to accept a decryption key index

rework decode_slatepack function to accept decryption key indices

---

src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

If a Slatepack address is provided, request a payment proof by default during the send command. If a proof is not desired, the user can pass the `-n` `--no-payment-proof` flag.

Request Payment Proof by default

---

api/src/owner.rs
config/src/types.rs
controller/src/command.rs
libwallet/src/api_impl/types.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Addresses #451. This is really the only non-breaking way to implement this (anything else would mean adding parameters to the `receive_tx` foreign API function, which would break backwards compatibility.
* Adds a `skip_send_attempt` field to the `TorConfig` struct. If set to `Some(true)`, the slatepack workflow will skip the Tor send attempt.
* To turn off TOR sends, via the API's, use the `set_tor_config` API function (included in both the Owner and Foreign APIs), setting `skip_send_attempt` to `true`
* In addition, all command-line functions that can send via Tor now take a `--manual, -m` flag. If present, the Tor send attempt will be skipped.

Add option to skip Tor send attempts in TorConfig

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/repost.rs
controller/tests/transaction.rs
libwallet/src/api_impl/owner.rs
libwallet/src/error.rs
libwallet/src/lib.rs
libwallet/src/slate_versions/v4.rs

Modifications to the `get_stored_tx` API function as raised in #452 
* `get_stored_tx` accepts either a transaction id or slate uuid
* `get_stored_tx` returns a Slate instead of a raw transaction. (Although a Slate that's been built from the stored transaction object, so it won't be the slate originally used to create the transaction).
* Command line remains the same, we can add the ability to repost by UUID later if needed.
Will likely be reworking/reducing the entire API and command line before 5.0.0, but this will make the existing API a bit cleaner for now.

Modify get_stored_tx API

---

controller/src/command.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Adds the `outfile` flag to all commands that output a slatepack. If provided, the backup slatepack file will be output to the specified location instead of the default `slatepack/[uuid].slatepack` location

Add flag to override location of slatepack output file

---

api/src/owner.rs

Past behavior of the `init_send_tx` method with InitSendTxArgs (only when the recipient wallet was reachable):
1. Sender sends transaction to recipient
2. Recipients receives it and send back
3. Sender lock outputs
4. Sender `finalise` iff InitSendTxArgs contains `finalize=true` and returns the final slate
5. Sender `post_tx`  iff InitSendTxArgs contains `post_tx=true`  and returns the final slate
Current behavior with the same condition:
1. Sender sends transaction to recipient
2. Recipients receives it and send back
3. A. If `post_tx=true` Sender lock outputs, finalize and post_tx iff `post_tx=true`  and returns the final slate
3. B. If `post_tx=false` Sender returns the first slate
This PR locks outputs, finalise and return the final transaction but do not post when `post_tx=false`. …

TxLock and finalize

---

controller/src/display.rs
impls/src/adapters/slatepack.rs
integration/tests/simulnet.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate_versions/v4.rs
libwallet/src/slatepack/armor.rs
libwallet/src/slatepack/packer.rs
libwallet/src/slatepack/types.rs
src/cmd/wallet_args.rs

* refactor to pass slice `&[u8]` around and not `&Vec<u8>`
* cleaned up a couple of `unwrap()` calls in `check_header()` and `check_footer()`
It is more idiomatic in rust to pass a slice into a fn.
This ends up cleaning up some of the surrounding code as the fn is a little more flexible this way.
I noticed this when reviewing the proposed slatepack size checks in #495.

refactor to pass slice &[u8] around and not &Vec<u8>

---

libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/types.rs
libwallet/tests/libwallet.rs

Now that slates contain their transaction state( S1, I2 etc), there should be no need for wallet to retain information about the type of transaction its dealing with. This removes this information from the stored context and simplifies some confusing leftover logic that was previously needed to determine what type and what stage a transaction was at.

Clean up - Remove invoice state from context

---

Cargo.lock
controller/tests/revert.rs
impls/src/test_framework/mod.rs
impls/src/test_framework/testclient.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs

Resolves https://github.com/mimblewimble/grin/issues/3415
Various transaction input related things got refactored and these changes account for this here.

tx inputs underwent refactoring

---

impls/src/adapters/slatepack.rs
libwallet/src/lib.rs
libwallet/src/slatepack/armor.rs
libwallet/src/slatepack/mod.rs
libwallet/src/slatepack/packer.rs

Check Slatepack file size is within valid range before loading contents into memory.

Check Slatepack file size before loading contents

---

Cargo.lock
impls/src/test_framework/mod.rs
impls/src/test_framework/testclient.rs

Related: https://github.com/mimblewimble/grin/pull/3423
Fix call to `chain.get_unspent()`

get_unspent api changed to take a commitment directly

---

Cargo.lock
impls/src/node_clients/http.rs
impls/src/test_framework/mod.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4.rs

Related: https://github.com/mimblewimble/grin/pull/3371
Grin reworked outputs to wrap a pair of output_identifier and rangeproof. This simplifies some internal code and reduces the amount of magic going on when hashing outputs, comparing outputs etc.
This PR updates the wallet code to match this.
----
Added test coverage for json serialization/deserialization of the transaction in `push_transaction` api call.

grin output_identifier refactoring

---

impls/src/node_clients/http.rs

Related: #516 
We call the `get_unspent_outputs` api and expect to receive a collection of unspent outputs.
This is a reasonable assumption but we are brittle on the receiving/parsing side as each output in the response _must_ contain a block height. If we receive a _spent_ output for any reason the wallet is rendered inoperable as we can no longer refresh outputs.
This PR adds a (hopefully redundant) level of robustness by explicitly filtering out spent outputs from the list returned by the api.
See #516 for some background where the node api was inadvertently changed to return spent and unspent outputs, causing the wallet to fail.

we expect unspent outputs but play it safe

---

.ci/release.yml
.ci/windows-release.yml

The CI produces `*-sha256sum.txt` files that look like this:
```
SHA256(/home/vsts/work/1/a/grin-wallet-v3.1.0-linux-amd64.tar.gz)= bdc0ea8b8163bee7265ed63ee525720f3ad511b984987189a719427362b00313
```
While ideally we'd want it to look like this:
```
SHA256(grin-wallet-v3.1.0-linux-amd64.tar.gz)= bdc0ea8b8163bee7265ed63ee525720f3ad511b984987189a719427362b00313
```
This would users to compare the binary with the checksum file using `sha256sum -c`.
On Windows a similar issue exists:
```
Algorithm : SHA256
Hash      : 6C1A28FA709EBFF0F142DE41209991ED58A89170927CF698974D25ED72D920D7
Path      : D:\a\1\a\grin-wallet-v3.1.0-win-x64.zip
```
To fix this, we first `cd` to the build directory and run the checksum generation command from there.
I have to set up a test CI on my repo to make sure …

CI: no directories in checksum file

---

Cargo.lock
impls/src/backends/lmdb.rs

Our low level lmdb iter usage changed in https://github.com/mimblewimble/grin/pull/3450
This PR reworks the wallet usage of `db.iter()` to reflect these changes.
This is just to get everything compiling. We should revisit this as the interface is a little awkward right now.

fix our lmdb iter usage to work with changes in grin

---

Cargo.lock
api/src/owner.rs
config/src/config.rs
impls/src/lifecycle/default.rs
impls/src/lifecycle/seed.rs
libwallet/src/types.rs
src/bin/grin-wallet.rs
src/bin/grin-wallet.yml
util/Cargo.toml

Equivalent of https://github.com/mimblewimble/grin/pull/3431. Tests won't pass until merged.
There is no migration setup so user will need to move/restore in the new `test` dir.

Rename Floonet to Testnet

---

src/bin/grin-wallet.yml

We use the `smallest` coin selection strategy by default when sending funds.
But we were defaulting to `all` when paying an invoice.
This PR standardizes both payments to use `smallest` consistently.

default to smallest strategy for paying invoices

---

api/src/owner.rs
config/src/types.rs
impls/src/adapters/http.rs
impls/src/adapters/mod.rs
impls/src/lib.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Implementation of the [Deprecate HTTP(S) Transactions RFC](https://github.com/mimblewimble/grin-rfcs/pull/54).

Deprecate HTTP(S)

---

.ci/windows-release.yml
Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Build `5.0.0-beta.2` ready for tagging.
* build `5.0.0-beta.2`
* use `5.0.0-beta.2` tag for grin crates
* fix wallet release script for windows on CI (`refreshenv`)
Replaces #535

build 5.0.0-beta.2

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/535 but for master branch.
- `4.1.0-alpha.1` -> `5.1.0-alpha.1`
- Update grin dependency to `master`

Bump master version to 5.1.0-alpha.1

---

controller/tests/late_lock.rs

This test was never actually posting the tx to the node.
The tx was never included in a block. Funds were never received by the receiving wallet.
* post late locked tx
* assert amount on both wallets
* cleanup wallet account setup

post late locked tx and assert amount on both wallets

---

impls/src/client_utils/client.rs

The HTTP client is currently used both outside and inside of a tokio runtime context. In the latter case we are not allowed to do a blocking call to our global runtime, which unfortunately means we have to spawn a new thread.
At the moment we are mixing asynchronous and synchronous contexts all over the place, which is not great. This means that we are blocking inside API calls, reducing the amount of concurrent request we could serve. In practice, this probably is not noticeable since the number of requests to a wallet API is usually not that huge. Additionally a lot of wallet operations require a write lock on the db, which means requests have to be handled in-part sequentially anyway.
Ideally, we'd move to fully asynchronous, but this would require a relatively large refactor of the …

[5.0.x] Fix panic when calling certain API endpoints

---

api/src/foreign_rpc.rs
api/src/owner.rs

`finalize_invoice_tx` no longer exists.

[5.0.x] Fix comment about deprecated method

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

~Hold off on merging this. We have a possible 5.0.1 for node.~
----
* bump version to ~`5.0.0`~ `5.0.1`
* point to published ~`5.0.0`~ `5.0.1` crates on crates.io for node deps

[5.0.x] bump version to 5.0.1

---

impls/src/node_clients/http.rs

When introducing the fix in https://github.com/mimblewimble/grin-wallet/pull/552 we missed the scan api method, since it uses a `FuturesUnordered` instead of `Client::send_request`.
Fixes https://github.com/mimblewimble/grin-wallet/issues/559.

[5.0.x] Fix owner API scan

---

libwallet/src/api_impl/owner.rs

The former aggregate_fee_fields(0) call would fail on huge fees.
The fixed one will always apply the fee mask.
It can still fail on a tx with multiple kernels whose fees add up to a huge one.
Merging this is not that urgent. Merge whenever convenient.

fix yet another instance of fee fields at height 0

---

libwallet/src/slate.rs

Just like `pub_blind_sum(&self, secp: &secp::Secp256k1)` is a public function `pub_nonce_sum(&self, secp: &secp::Secp256k1)` and `msg_to_sign(&self)` should be too, as wallets that generate signatures outside of the slate context (not by using `fill_round_2`) have to have access to those values.
For instance in cases where signing requires a different approach than what is implemented in `fill_round_2` such as where a secret key and nonce for a coin is split between two parties rather than one.

Changed pub_nonce_sum and msg_to_sign to be public functions

---

impls/src/node_clients/http.rs

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/573 for master

Fix owner API scan

---

controller/src/command.rs
controller/src/controller.rs
impls/src/adapters/file.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate_versions/v4_bin.rs
src/cmd/wallet_args.rs

To make these easy to review, these are nice obvious wins that make the code smaller and cleaner. :)
All of the removed `clone()`s are unnecessary, usually because that type implements `Copy`.
`cargo test --all` passes locally.

Clippy easy wins

---

controller/src/controller.rs
src/bin/grin-wallet.yml

From https://support.torproject.org/about/#why-is-it-called-tor
> Note: even though it originally came from an acronym, Tor is not spelled "TOR". Only the first letter is capitalized. In fact, we can usually spot people who haven't read any of our website (and have instead learned everything they know about Tor from news articles) by the fact that they spell it wrong.

Change to proper spelling of Tor

---

.ci/release.yml
.ci/test.yml
.ci/windows-release.yml
Cargo.lock
impls/src/test_framework/testclient.rs
libwallet/src/slate.rs

As reported by @tromp in keybase://chat/grincoin.teams.wallet_dev#general/8552 :
>it looks like grin-wallet is out of sync with grin ?!
>grin master removed verifier cache from calls like Chain::init
>but it's still passed in e.g. https://github.com/mimblewimble/grin-wallet/blob/master/impls/src/test_framework/testclient.rs#L105
>shldn't there be a grin-wallet complement to your commit https://github.com/mimblewimble/grin/commit/f6ec77a592de04fcc4a78127822932ec7e18525c  ?
Bumps `Cargo.lock` `mimblewimble/grin` git dependencies to latest commit https://github.com/mimblewimble/grin/commit/f6ec77a592de04fcc4a78127822932ec7e18525c and fixes the disappearance of the verifier cache.
`cargo test --all` passes locally.
Unblocks #479.

Sync to latest grin master and fix missing verifier_cache

---

controller/src/command.rs

Fixes #582 "grin-wallet crashes when attempting to send amount larger than balance":
```
$ grin-wallet send -e -m 220.5
Password: 
Wallet command failed: LibWallet Error: Not enough funds. Required: 220.512000000, Available: 0.000000000
$
```
`cargo test --all` passes locally.

Bubble `init_send_tx` error instead of unwrapping

---

.ci/test.yml
.ci/windows-release.yml

Counterpart to https://github.com/mimblewimble/grin/pull/3632, fixes Windows `cargo test` to actually test instead of silently passing.

Fix Windows CI `cargo test` silently passing

---

Cargo.lock
controller/src/display.rs
controller/tests/transaction.rs
impls/src/test_framework/mod.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4_bin.rs

name: fixpastfees
about: remove dependence of fee() and fee_shift() functions on height
title: 'fix past fees'
Companion PR for
https://github.com/mimblewimble/grin/pull/3629
both implementing RFC https://github.com/mimblewimble/grin-rfcs/blob/master/text/0021-fix-prior-fees.md
to extend the 40 bit fee restriction and use of fee shifts back beyond HF4 to all history.
Technically a Hard Fork, but if we have a many month reorg introducing a > 40 bit fee prior to HF4, we have bigger problems to deal with than a chain split.
This simplifies all fee related functions as they no longer need a height argument to distinguish preHF4 from postHF4 behaviour.

remove height argument from fee related functions as per fixpastfees RFC

---

controller/src/controller.rs

Adds dyn keyword to OwnerRpc and ForeignRpc trait objects
Fixes deprecation warning

Fix deprecated use of RPC trait object without dyn

---

Cargo.lock
impls/src/backends/lmdb.rs
libwallet/src/slate_versions/v4_bin.rs
libwallet/src/slatepack/types.rs

With the PR #630, I need to fetch actually the lastest master. But the test are failing due to the fact that the des&ser function are taking additional arguments with this new commit https://github.com/mimblewimble/grin/commit/63c65605bbe7a3ee4a8805c7f5aa7e7e153a15d5

Update to latest master and ser&des fn arguments

---

Cargo.lock
impls/src/test_framework/testclient.rs

Fixes an intro introduced by recent PMMR indexing changes in `get_outputs_by_pmmr_index` API function by ensuring it never passes in a zero to a 1-based call.

pmmr indexing related fix for get_outputs_by_pmmr_index function

---

api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/src/display.rs
libwallet/src/api_impl/owner.rs
libwallet/src/error.rs
libwallet/src/internal/scan.rs
libwallet/src/lib.rs
libwallet/src/types.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

Re-opening the PR here. (old #630)
Features (api&cmdline):
- get the rewind_hash of the wallet
- scan of the rewind_hash of a third-party wallet
Goal:
Ensure the transparency (spending, receiving, balance etc) of a wallet that receive grin as donations.
Allow everyone to scan the rewind_hash of the wallet shared publicly.
Cmd usage:
get_rewind_hash: `grin-wallet rewind_hash`
scan_rewind_hash: `grin-wallet scan_rewind_hash 2c95b24de492395934a8a345440ed0ebbe67ee0025b348712a927a91c7fe58e9`
@yeastplume --> Just a note for anyone watching, this PR just provides an API for the post 2.0.0 BP rewind scheme outlined and decided upon prior to the 2.0.0 hardfork here: #105. This just covers public view keys and obviously won't work with any outputs created prior to 2.0.0.

View Wallet - fn rewind_hash & scan_rewind_hash

---

impls/src/adapters/http.rs
impls/src/client_utils/client.rs

Took two small changes to get the socks5 proxy support working. Opened here for consideration.

Fix socks5 proxy support

---

impls/src/client_utils/client.rs
impls/src/node_clients/http.rs

Attempt to fix #639. 
Basically, I believe that recent changes to tokio are forcing panic when a worker thread attempts to block, causing a panic on futures that block while calling out to the node. The fix here is to ensure another thread is spawned to handle blocking requests, and ensuring they're properly `awaiting` the result.

Send API tokio worker panic fix

---

config/src/comments.rs

Previous Merged PR #617 contains config file migration functionality, however this was failing on very old wallet files due to a missing comment entry for `skip_send_attempt`. This adds the comment and allows older wallet files to migrate successfully.

Config file migration fix

---

Cargo.lock
controller/src/controller.rs
tests/common/mod.rs

* Updates to ensure compilation against Grin 5.1.2 and preparation for release
* Add API channel to grin API startup call
* Add `Timeout` to grin API client call
* Update `Cargo.toml` dependencies

Grin 5.1.2 Updates

---

azure-pipelines.yml

Looks like the newest version of the runner does not include llvm anymore. This PR fixes the CI and unblocks #650.

Fix macOS CI tests

---

src/cmd/wallet_args.rs

It makes no sense to ask for the password if one only wants to initialize the APIs. Asking for the password makes things unnecessarily difficult and insecure in case I, as a system administrator, want to have the APIs running as a system service.

Do not prompt for password to start owner API

---

Cargo.lock
controller/Cargo.toml
controller/src/controller.rs

Resolves https://github.com/mimblewimble/grin-wallet/issues/649.
To see it in action, compile and run `grin-wallet listen`. You will see your Slatepack address as usual, but now also with a scanable QR code:
```bash
$ grin-wallet listen
Password:
20220626 22:39:35.332 WARN grin_wallet_controller::controller - Starting Tor Hidden Service for API listener at address x5fnata4ge6fbj35hwojo2eynhxq5lgzr6e3q4lbd4unoxfmekbzw7qd, binding to 127.0.0.1:3415
20220626 22:39:37.720 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 127.0.0.1:3415.
20220626 22:39:37.721 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20220626 22:39:37.722 WARN grin_wallet_controller::controller - Slatepack Address is: …
```

Show QR code for listener address

---

controller/src/command.rs
controller/tests/transaction.rs
libwallet/src/api_impl/owner.rs
libwallet/src/api_impl/types.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs
tests/cmd_line_basic.rs
tests/data/v3_reqs/init_send_tx.req.json

This feature consists of three commits:
1) Extend API to allow "fee inclusive" transaction amounts
2) Expose this option in the CLI `send` command via new flag: `--amount_includes_fee`
3) Calculate & spend max wallet balance, if 'max' keyword is used as send amount
I've added tests for all three commits as well as functionally tested with real coins in a real wallet.
@yeastplume @phyro as written today, I think this incurs a breaking API change. I tried to come up with an approach that would be backwards compatible, but I kept having to resort to hacks and abuse of other args to make it happen... I decided it would be better to implement this logic "properly" for now, and see how bad the pushback is for making a breaking change to the API :grimacing:. Please let me know your thoughts. …

Implement fee inclusive transactions

---

controller/src/command.rs
src/bin/grin-wallet.yml
src/cmd/wallet_args.rs

This PR adds a `--count` option to the `txs` wallet command, to restrict the number of TXs shown. I find this very helpful when working in wallets with many transactions. Example usage:
```
$ grin-wallet txs --count 10
```
This is a CLI change only, which I think is useful today. As I outline in https://github.com/mimblewimble/grin-wallet/issues/659, it might also be worth modifying the API to allow constrained queries to the wallet.

Add option to limit number of TXs shown

---

azure-pipelines.yml

Ubuntu image 18.04 has been deprecated by azure pipelines. This updates the CI build to use latest ubuntu image 22.04.

CI update - Ubuntu Image

---

Cargo.lock
api/src/foreign_rpc.rs
api/src/owner_rpc.rs
impls/src/adapters/http.rs
libwallet/Cargo.toml
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v5.rs
libwallet/src/slate_versions/v5_bin.rs

Slate V5 changes in order to provide experimental support to [Early Payment Proofs](https://github.com/mimblewimble/grin-rfcs/pull/70#pullrequestreview-1352319887) for use with contract transaction workflows. This aims to provide the new slate fields in a V5 Slate as well as provide all needed v4 conversions and tests. 
Specific slate changes are [WIP]:
PaymentInfoV5 Struct
* `saddr`, i.e. `sender_address` in main Slate becomes optional
* `rsig` is renamed to `psig`, corresponding to rename of `receiver_signature` to `promise_signature` in main Slate
* `ts` added (`timestamp` in main slate). Serialized as i64 representing epoch time in seconds
* `memo` added as optional MemoV5 Struct, which contains:
* `memo_type`: u8
* 0x00 = payment details directly embedded
* 0x01 = Blake2b hash of an …

[Contracts] Experimental Slate v5

---

Cargo.lock
api/src/owner.rs
controller/tests/self_send.rs
impls/Cargo.toml
impls/src/tor/process.rs

Due to changes in rust, compilation was failing on windows and we need to update the sysinfo crate used by tor process handling to the latest. This also comes with API changes, namely that the `Process` struct can't be instantiated directly and needs to be searched in the `System` struct. 
Changes now needs to be sanity tested on all platforms to ensure tor processes still start and terminate as expected.
Also contains updates to remove deprecation warnings from chrono related updates.

Update sysinfo crate to 0.29.6

---

README.md

As titled. Replace Azure Pipelines by Github Actions Badge.

Update CI Badge on README.MD

---

Cargo.lock
Cargo.toml
README.md
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Update versioning to 5.2.0-beta.1 against grin 5.2.0-beta.3

---

api/src/foreign.rs
api/src/owner_rpc.rs
controller/tests/common/mod.rs
controller/tests/contract_accounts.rs
controller/tests/contract_accounts_switch.rs
controller/tests/contract_early_lock.rs
controller/tests/contract_early_proofs.rs
controller/tests/contract_rsr.rs
controller/tests/contract_srs.rs
impls/src/backends/lmdb.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/contract/actions/revoke.rs
libwallet/src/contract/actions/view.rs
libwallet/src/contract/proofs.rs
libwallet/src/contract/slate.rs
libwallet/src/contract/types.rs
libwallet/src/contract/utils.rs
libwallet/src/error.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v5_bin.rs

* Cleanup of warnings throughout
* Modify existing contract tests to take early payment proofs into account - either proofs need to be explicitly turned off in code or you need to supply a receiver address, mix of both sprinkled throughout (need to think about this).
* General cleanup in preparation for some more contracts/payment proof testing, to be integrated into the gui wallet in turn

Contracts - Test fixes + warning cleanups

---

controller/tests/contract_self_spend.rs
controller/tests/contract_self_spend_custom.rs
libwallet/src/api_impl/types.rs
libwallet/src/contract/actions/sign.rs
libwallet/src/contract/utils.rs
libwallet/src/internal/updater.rs
libwallet/src/types.rs

* Adds an explicit `SelfSpend` transaction state, at the moment only set during contracts workflow.
* Sets the type on a transaction during contract workflow when the number of participants in the slate is set to 1
Note this would have a lot of extra areas that needs to be addressed were it used in the legacy wallet workflow. This included on the contracts branch only for experimental purposes and reflected only in the gui project for now.

[Contracts] Add self spend transaction state

---

controller/tests/contract_early_proofs_rsr.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/mod.rs
libwallet/src/slate_versions/v5_bin.rs
libwallet/src/slatepack/packer.rs

Fix to subtle bug preventing slatepacked slates deserializing payments proof properly, thus preventing RSR contracts transactions working within the GUI wallet. Basically, an enum's fields were in the wrong order.
Adds tests in a few places to check for this in future.

[Contracts] Slatepack v5 Deserialization fix

---

controller/tests/contract_self_spend_cancel.rs
libwallet/src/internal/tx.rs
libwallet/src/internal/updater.rs

Uncovered via https://github.com/mimblewimble/grin-gui/issues/82, self-spend transactions previously uncancellable due to the `tx_cancel` function not handling the transaction type properly.
* Updates cancel function to handle explicit self-spends
* Ensure cancelled self spend transactions are properly filtered by advanced query filter
* add cancel test for self-spend transactions

Add Self-Spend Cancel + Tests

---

controller/tests/invoice.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/error.rs

Finalize methods for owner and foreign API were taking different paths, leading to invoice transactions not being handled correctly when finalize was called via the owner API. 
* Unify logic into single function and simply call the foreign version from the owner API.
* Add test case to cover calling finalize with an invoice transaction from owner API
Fixes #635

Unify owner + foreign API finalize

---

controller/tests/invoice.rs
libwallet/src/api_impl/owner.rs
libwallet/src/error.rs

Prevents #706, more correct behavior is to not attempt to re-pay a transaction that's been cancelled. Payee should request a new invoice in this case.

Prevent wallet attempting to re-pay a cancelled invoice transaction

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

* Update version to 5.3.0 to match node release
* Update imported version of Grin crates to 5.3.0
* Cargo update run on `Cargo.lock`

Update versioning, dependencies for 5.3.0 release

---

config/src/types.rs

* The listen interface for the owner API is currently hardcoded to `127.0.0.1`. We'd previously resisted allowing this to be opened up (by, say changing the interface to `0.0.0.0`), as a security measure to ensure clients to the owner interface are limited to being on the same machine.
This is probably far too limiting, and in particular makes docker deployments difficult as there's no way to access the wallet APIs at all from outside the deployed container, (which is necessarily set up to run the owner API as a service and nothing else). 
This PR adds `owner_api_listen_interface` as a configuration field, but doesn't output the field into the configuration file by default, i.e. a user will really need to know what they're doing in order to enable this field. This should provide a good …

[CONTRACTS] Add `owner_api_listen_interface` as hidden configuration field

---

.cargo/config
Cargo.lock
Cargo.toml
impls/src/adapters/mod.rs
impls/src/node_clients/resp_types.rs
src/build/build.rs

Redo after code intended for contracts branch was accidentally introduced into master and then reverted.
* Update built crate to 0.7
* Remove warnings, allow dead_code when necessary
* Rename `.cargo/build` to `.cargo/build.toml
`

[MASTER] Updates for Rust 1.80+

---

impls/src/adapters/http.rs
impls/src/client_utils/client.rs
impls/src/node_clients/http.rs

With current implementation we could not provide proxy configuration to `HTTPNodeClient` on wallet creation for RPC communication, also there was hardcoded `socks5h` scheme used for Tor client at another place.

Provide proxy on node client creation
