Cargo.lock
refwallet/src/lmdb_wallet.rs

Wallet portion of https://github.com/mimblewimble/grin/pull/2656

Database naming consistency with 1.0.x

---

Cargo.lock
api/src/foreign.rs
api/src/foreign_rpc.rs
api/src/owner.rs
api/src/owner_rpc.rs
controller/src/command.rs
controller/tests/file.rs
controller/tests/repost.rs
controller/tests/self_send.rs
impls/src/adapters/keybase.rs
impls/src/test_framework/testclient.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/types.rs

Completes rustdoc function and RPC documentation for the ForeignAPI

Foreign API documentation and small cleanup

---

README.md

Replace existing badges with SVG counterparts and add a bunch of new ones.

docs: update/add new README.md badges

---

impls/src/node_clients/http.rs
src/bin/cmd/wallet_args.rs

Fixes #40 and temp fix for #37

Command line port fix + query chunk size fix

---

README.md
api/src/owner_rpc.rs

Provide some basic info in the Readme and fix #102

Doc fix and filling out readme

---

impls/src/error.rs
impls/src/seed.rs

More helpful error message on recover when `wallet_data` dir doesn't exist

---

controller/src/controller.rs
impls/src/adapters/http.rs

Aims to
* Remove all trace of V1 Wallet API
* Implement wallet-to-wallet communication via the V2 API

V1 API + V2 wallet to wallet impl

---

src/bin/cmd/wallet.rs

Clearer user messaging when node in use is 1.1.0 or less

---

controller/src/command.rs
src/bin/cmd/wallet_args.rs
src/bin/cmd/wallet_tests.rs
src/bin/grin-wallet.rs
src/bin/grin-wallet.yml

Merge master into milestone/2.1.0

---

util/Cargo.toml

Small PR, remove version for local testing (will not work otherwise).

Fix local testing Cargo.toml

---

Cargo.lock
util/Cargo.toml

Versioning for 2.1.0-beta.1 release

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

bump version v2.1.0-beta.2

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version bump for beta.3

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
impls/src/adapters/http.rs
impls/src/adapters/mod.rs
libwallet/Cargo.toml
util/Cargo.toml

Cherry-pick of #236 (Plus sneaking in beta version increment)

2.1.x url fix

---

Cargo.lock

Update easyjson-rpc-mw to 0.5.4

---

libwallet/src/types.rs

Cherry pick #242

---

libwallet/src/slate.rs

Fix incorrect ttl type merged by accident (by me) in #263

Fix incorrect merge in previous PR

---

Cargo.lock
config/src/config.rs

Wallet-side version of changes found in https://github.com/mimblewimble/grin/pull/3124/files

Fixes for log level compatibility

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Versioning for 3.0.0-beta.2

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Updated to link v3.0.0-beta.3 node release

---

impls/src/node_clients/http.rs

Cherry pick of #285 into master

Fix to unwraps (#285)

---

.hooks/pre-commit
src/cmd/wallet.rs

Version check fix + Rustfmt (#293)

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Performing a beta build of 3.0.1

Versioning for 3.0.1-beta.1

---

config/src/comments.rs
config/src/config.rs
config/src/types.rs
controller/src/display.rs
libwallet/src/slate.rs
util/src/ov3.rs

Remove cloning and various formating/efficiency improvements

---

Cargo.lock

Probably forgotten from https://github.com/mimblewimble/grin-wallet/pull/295.

Add Cargo.lock

---

api/src/types.rs
impls/src/lifecycle/seed.rs

Ongoing changes to fix issues caused by upstream ring version increment.

Update and confirm new ring::aead version

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version increment for 3.1.0-beta.2

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version bump for 3.1.0 release

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Merge after https://github.com/mimblewimble/grin-wallet/pull/357

Update version to v3.1.1

---

api/src/owner_rpc.rs
controller/tests/invoice.rs
controller/tests/no_change.rs
controller/tests/payment_proofs.rs
controller/tests/repost.rs
controller/tests/transaction.rs
controller/tests/ttl_cutoff.rs
impls/src/adapters/file.rs
impls/src/adapters/http.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/tx.rs
libwallet/src/lib.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4.rs

* Add `SlateState` and `SlateStateV4` enums as per RFC
* Set correct slate state at each state in process + tests

Add State Slate

---

controller/tests/payment_proofs.rs
controller/tests/transaction.rs
libwallet/src/api_impl/owner.rs
libwallet/src/internal/selection.rs
libwallet/src/internal/tx.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/v4.rs

* Change `num_participants` to `u8` from `Option<usize>`, rename to `num_parts`
* Change `lock_height` to `u64` from `Option<u64>`, rename `lock_hgt`
* Change `ttl_cutoff_height` to `u64` from `Option<u64>`, rename `ttl`

V4 Slate field tweaks

---

api/src/foreign.rs
api/src/foreign_rpc.rs
api/src/owner.rs
api/src/owner_rpc.rs
libwallet/src/api_impl/foreign.rs
libwallet/src/api_impl/owner.rs
libwallet/src/slate.rs

Various fixes to json-rpc doctests, not yet 100% complete since some functions that operation on the transaction object need to be looked at.

Doctest Fixes for compact slate branch

---

Cargo.lock
api/src/types.rs
controller/src/display.rs
impls/src/backends/lmdb.rs
impls/src/lifecycle/seed.rs
impls/src/node_clients/http.rs
impls/src/test_framework/testclient.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/types.rs

Update and fixes for `to_hex()`

Update grin from master

---

Cargo.lock
api/src/types.rs
controller/src/display.rs
impls/src/backends/lmdb.rs
impls/src/lifecycle/seed.rs
impls/src/node_clients/http.rs
impls/src/test_framework/testclient.rs
libwallet/src/slate.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/types.rs

Resolves #401.
Fixes - 
* `to_hex()`
* `read<R: ser::Reader>`

grin-wallet master now building against grin master

---

Cargo.lock
controller/src/display.rs
impls/src/backends/lmdb.rs
libwallet/src/slate_versions/ser.rs
libwallet/src/slate_versions/v4_bin.rs
libwallet/src/types.rs

Merge latest changes to compact slate branch from upstream based on #402

Merge master

---

api/src/foreign.rs
api/src/owner.rs

Test to check apparently random CI failures. The PR that produced this version of master and the test run after it was merged all passed CI without issue, yet PR #412 is consistently failing.

Don't run doctests on Windows CI

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version Bump for v4.0.0-beta.1

---

api/src/owner_rpc.rs
libwallet/src/slatepack/address.rs
libwallet/src/slatepack/types.rs
tests/cmd_line_basic.rs

Calling it.
* `grin1` on mainnet
* `tgrin1` for floonet or any other testing chain type
(Last change before beta.2, and last intended functional change for 4.0.0 overall)

Slatepack Address HRP

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version Bump for v4.0.0-beta.2

---

api/src/owner_rpc.rs

Remove newline from `create_slatepack_message` JSON API Output

---

controller/src/command.rs

As suggested in #443, adjusts finalize output to be consistent with output from other commands

Adjust slatepack finalize --nopost output

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version bump for 4.0.0-beta.3

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Version bump to v4.0.0-rc.1

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Versioning for 4.0.0

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Also building with grin master instead of 4.0.0 tag

version bump for next potential release

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR adds Bug Report and Feature Request templates to grin-wallet's issues.

Add issue templates for grin-wallet

---

.ci/test.yml

Related: https://github.com/mimblewimble/grin/pull/3498

call refreshenv as part of windows test script

---

config/src/comments.rs

Just a minor PR to remove unused code after having deprecate http(s).

remove api_listen_interface - unused

---

controller/src/command.rs
src/cmd/wallet_args.rs

Same as https://github.com/mimblewimble/grin-wallet/pull/545 but for the 5.0.x branch.

[5.0.x] Fix error when estimating fees for selection strategies

---

controller/src/command.rs
src/cmd/wallet_args.rs

Fixes https://github.com/mimblewimble/grin-wallet/issues/528.

Fix error when estimating fees for selection strategies

---

config/src/config.rs
config/src/types.rs

Fix of bladedoyle issue Grinnode-live/2020-grin-bug-bash-challenge#15

[5.0.x] replace .api_secret to .foreign_api_secret

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

[5.0.x] Bump version to 5.0.0-beta.3

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Update wallet to beta.4. Node stays in beta.3

[5.0.x] Bump version to 5.0.0-beta.4

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Both wallet and node dependencies.

[5.0.x] bump version to 5.0.0-rc.1

---

azure-pipelines.yml

Cherry picked from `master` (#562).

[5.0.x] Downgrade to ubuntu-18.04 (#562)

---

Cargo.lock

Cargo lock was not updated with #566.

[5.0.x] Fix Cargo lock

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

[5.0.x] Prepare v5.0.2 release

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

As titled. Hotifx for wallet owner API.

[5.0.x] Prepare for v5.0.3 release

---

api/src/foreign_rpc.rs
api/src/owner_rpc.rs

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/578 for master

Fix doctest

---

config/src/config.rs
config/src/types.rs

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/546 for master

replace .api_secret to .foreign_api_secret

---

impls/src/client_utils/client.rs

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/552 for master

Fix panic when calling certain API endpoints

---

api/src/foreign_rpc.rs
api/src/owner.rs

Equivalent of https://github.com/mimblewimble/grin-wallet/pull/550 for master

Fix comment about deprecated method

---

Cargo.lock
Cargo.toml
controller/Cargo.toml

* Verified issue in #673 on running installation
* Had cursory look at dependency updates involved in bumping the version of prettytable-rs
* Manually implement #668

Manual update and verification of prettytable-rs update

---

config/src/config.rs

As titled. Fixes https://github.com/mimblewimble/grin-wallet/issues/683.

Fix build error with Rust 1.71.0

---

.github/workflows/ci.yaml

As titled. Forgot about that part.

Trigger CI on push and pull request

---

controller/tests/contract_early_proofs_rsr.rs
controller/tests/contract_early_proofs_srs.rs

* Split tests into explicit RSR and SRS workflows with proof generation in all cases
* Add RSR workflow test

[Contracts] Added explicit payment proof tests for both RSR and SRS workflows

---

controller/tests/self_send_cancel.rs
libwallet/src/internal/tx.rs

[Contracts] Cancel self-spend TX Pt. 2

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

as titled, only change is underlying inclusion of grin_secp256k1 to 0.7.14

Update and versioning for v5.3.1

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

Reverts mimblewimble/grin-wallet#709 - (merged to wrong branch)

Revert "Update and versioning for v5.3.1"

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

* Working master version to `5.4.0-alpha.1`
* Grin dependencies to `master`

Update working version on master

---

Cargo.lock
Cargo.toml
api/Cargo.toml
config/Cargo.toml
controller/Cargo.toml
impls/Cargo.toml
libwallet/Cargo.toml
util/Cargo.toml

* Versioning for 5.4.0_alpha_1 release, containing updates in #726

Versioning Updates for 5.4.0_alpha.1 release
